import { Show } from "./../model";

export const show: Show[] = [
    {
      id: 3,
      name: "L'impro fait sa rentrée",
      date: 1664476200,
      description:
        "💥 !! C’EST LA RENTRÉE !!💥\nPublic, nous sommes de retour sur les planches de la salle Le Cap 🎭 !!\nEt on te prépare un match de rentrée inoubliable 😍\nSi tu ne connais pas le théâtre d’improvisation, ce sera une très belle occasion de le découvrir. Et qui sait, ça te donnera peut-être envie de nous rejoindre !! 🎭❤️",
      freeForStudents: true,
      location: "Salle Le CAP",
      imgLink: "https://zupimages.net/up/22/35/y42l.png",
      bannerImgLink: "",
      reservationLink: "https://luditoulouse.festik.net/",
      facebookLink: "https://www.facebook.com/events/641906803925821",
      instagramLink: "",
      isPublished: true,
      isHighlighted: false,
      price: 5,
      reducedPrice: 3,
    },
    {
      id: 4,
      name: "Cours d'essais",
      date: 1664476200,
      description: "",
      freeForStudents: false,
      location: "Bâtiment U2 Université Paul Sabatier ",
      imgLink: "",
      bannerImgLink: "",
      reservationLink: "",
      facebookLink: "",
      instagramLink: "",
      isPublished: true,
      isHighlighted: false,
      price: 0,
      reducedPrice: 0,
    },
    {
      id: 5,
      name: "Cours d'essais",
      date: 1664476200,
      description: "",
      freeForStudents: false,
      location: "Bâtiment U2 Université Paul Sabatier ",
      imgLink: "",
      bannerImgLink: "",
      reservationLink: "",
      facebookLink: "",
      instagramLink: "",
      isPublished: true,
      isHighlighted: false,
      price: 0,
      reducedPrice: 0,
    },
    {
      id: 9,
      name: "Catch Oboudup ",
      date: 1664476200,
      description: "",
      freeForStudents:  false,
      location: "Bar O Boudu Pont",
      imgLink: "",
      bannerImgLink: "",
      reservationLink: "",
      facebookLink: "",
      instagramLink: "",
      isPublished: true,
      isHighlighted: false,
      price: 0,
      reducedPrice: 0,
    },
    {
      id: 6,
      name: "Cours d'essais",
      date: 1664476200,
      description: "",
      freeForStudents: false,
      location: "Bâtiment U2 Université Paul Sabatier ",
      imgLink: "",
      bannerImgLink: "",
      reservationLink: "",
      facebookLink: "",
      instagramLink: "",
      isPublished: true,
      isHighlighted: false,
      price: 0,
      reducedPrice: 0,
    },
    {
      id: 7,
      name: "Cours d'essais",
      date: 1664476200,
      description: "",
      freeForStudents: false,
      location: "Bâtiment U2 Université Paul Sabatier ",
      imgLink: "",
      bannerImgLink: "",
      reservationLink: "",
      facebookLink: "",
      instagramLink: "",
      isPublished: true,
      isHighlighted: false,
      price: 0,
      reducedPrice: 0,
    },
    {
      id: 10,
      name: "Catch Oboudup ",
      date: 1664476200,
      description: "",
      freeForStudents: false,
      location: "Bar O Boudu Pont",
      imgLink: "",
      bannerImgLink: "",
      reservationLink: "",
      facebookLink: "",
      instagramLink: "",
      isPublished: true,
      isHighlighted: false,
      price: 0,
      reducedPrice: 0,
    },
    {
      id: 11,
      name: "Match au CAP",
      date: 1668108600,
      description: "",
      freeForStudents: false,
      location: "Salle Le CAP",
      imgLink: "",
      bannerImgLink: "",
      reservationLink: "https://luditoulouse.festik.net/",
      facebookLink: "",
      instagramLink: "",
      isPublished: true,
      isHighlighted: false,
      price: 7,
      reducedPrice: 5,
    },
    {
      id: 12,
      name: "Catch Oboudup ",
      date: 1668713400,
      description: "",
      freeForStudents: false,
      location: "Bar O Boudu Pont",
      imgLink: "",
      bannerImgLink: "",
      reservationLink: "",
      facebookLink: "",
      instagramLink: "",
      isPublished: true,
      isHighlighted: false,
      price: 0,
      reducedPrice: 0,
    },
    {
      id: 13,
      name: "Match au CAP",
      date: 1669318200,
      description: "",
      freeForStudents: false,
      location: "Salle Le CAP",
      imgLink: "",
      bannerImgLink: "",
      reservationLink: "https://luditoulouse.festik.net/",
      facebookLink: "",
      instagramLink: "",
      isPublished: true,
      isHighlighted: false,
      price: 7,
      reducedPrice: 5,
    }
];
