import { Show } from "./../model";

export const show: Show[] =
  [
    {
        "id": 21,
        "name": "Championnat IMPROVISEM ",
        "date": 1716921000,
        "description": "IMPROVISEM, notre championnat interne, revient pour une saison 2023-2024 qui commence dès ce mois de novembre !\nLes équipes des rouges, noirs, blancs et jaunes n'attendent qu'une chose : en découdre sur scène !\nVenez les voir s'affronter dans des matchs d'improvisation au sein de la Turbine ! \n\nÀ la fin, il n'y aura qu'un vainqueur…",
        "shortDescription": "Improvisem, notre championnat interne continue sa saison 2023-2024",
        "freeForStudents": false,
        "location": "La turbine - métro palais de justice",
        "imgLink": "https://luditoulouse.org/assets/logo/improvisem.png",
        "logoLink": "https://luditoulouse.org/assets/logo/improvisem.png",
        "bannerImgLink": "",
        "reservationLink": "",
        "facebookLink": "",
        "instagramLink": "",
        "isPublished": true,
        "isHighlighted": false,
        
        "price": 0,
        "reducedPrice": 0
    },
    {
        "id": 34,
        "name": " MAXI BEST OF de la Ludi",
        "date": 1717179300,
        "description": "\"Tu fais avec le budget que je te file\" Simon de la trésorerie. Bah du coup, c'est lui qui a fait le visuel 😕\n\nOn se retrouve le 31 mai pour une remake du Dixit et d'Hunger Games la team 😎",
        "shortDescription": "\"Tu fais avec le budget que je te file\" Simon de la trésorerie. Bah du coup, c'est lui qui a fait le visuel 😕\n\nOn se retrouve le 31 mai pour une remake du Dixit et d'Hunger Games la team 😎",
        "freeForStudents": false,
        "location": "Salle Le CAP - Métro Paul Sabatier",
        "imgLink": "https://i.ibb.co/g3MPTrZ/Maxi-Best-of-2024-Cadeau-Joueur-1.jpg",
        "logoLink": "https://i.ibb.co/g3MPTrZ/Maxi-Best-of-2024-Cadeau-Joueur-1.jpg",
        "bannerImgLink": "",
        "reservationLink": "https://www.helloasso.com/associations/ludi-toulouse/evenements/maxi-best-of-de-la-ludi",
        "facebookLink": "",
        "instagramLink": "",
        "isPublished": true,
        "isHighlighted": true,
        
        "price": 5,
        "reducedPrice": 3
    },
    {
        "id": 47,
        "name": "Catch D'Impro",
        "date": 1717698600,
        "description": "AIE AIE AIE : UN CATCH D'IMPRO SAUVAGE APPARAIT\nTu ne sais pas ce qu'est un catch d'impro ?\nPas de panique, je vais t'expliquer : c'est quatre improvisateurs repartis en deux équipes s'affrontent de manière plus dynamique qu'un match. Des thèmes plus WTF, aucun répit avant de monter sur scène et un spectacle encore plus intense avec toi, oui toi, public !",
        "shortDescription": "Improvisation en 2v2, nerveux et avec qu'une seule règle : c'est autorisé si le public rit.",
        "freeForStudents": false,
        "location": "Bar O Boudu Pont",
        "imgLink": "https://luditoulouse.org/assets/logo/catch.png",
        "logoLink": "https://luditoulouse.org/assets/logo/catch.png",
        "bannerImgLink": "",
        "reservationLink": "",
        "facebookLink": "",
        "instagramLink": "",
        "isPublished": true,
        "isHighlighted": false,
        
        "price": 0,
        "reducedPrice": 0
    },
    {
        "id": 27,
        "name": "Championnat IMPROVISEM - PETITE FINALE",
        "date": 1718130600,
        "description": "IMPROVISEM, notre championnat interne, revient pour une saison 2023-2024 qui commence dès ce mois de novembre !\nLes équipes des rouges, noirs, blancs et jaunes n'attendent qu'une chose : en découdre sur scène !\nVenez les voir s'affronter dans des matchs d'improvisation au sein de la Turbine ! \n\nÀ la fin, il n'y aura qu'un vainqueur…",
        "shortDescription": "Improvisem, notre championnat interne continue sa saison 2023-2024",
        "freeForStudents": false,
        "location": "La turbine - métro palais de justice",
        "imgLink": "https://luditoulouse.org/assets/logo/improvisem.png",
        "logoLink": "https://luditoulouse.org/assets/logo/improvisem.png",
        "bannerImgLink": "",
        "reservationLink": "",
        "facebookLink": "",
        "instagramLink": "",
        "isPublished": true,
        "isHighlighted": false,
        
        "price": 0,
        "reducedPrice": 0
    },
    {
        "id": 51,
        "name": "Les Impros de la Cartoucherie",
        "date": 1718737200,
        "description": "",
        "shortDescription": "Le Lud'Idée : terrain d'exploration de la LUDI. Chaque mois, découvrez un concept maison directement au 500",
        "freeForStudents": false,
        "location": "Bar les 500 - Arrêt Cartoucherie",
        "imgLink": "https://luditoulouse.org/assets/logo/ludidee.png",
        "logoLink": "",
        "bannerImgLink": "",
        "reservationLink": "",
        "facebookLink": "",
        "instagramLink": "",
        "isPublished": true,
        "isHighlighted": false,
        
        "price": 0,
        "reducedPrice": 0
    },
    {
        "id": 28,
        "name": "Championnat IMPROVISEM - GRANDE FINALE",
        "date": 1719340200,
        "description": "IMPROVISEM, notre championnat interne, revient pour une saison 2023-2024 qui commence dès ce mois de novembre !\nLes équipes des rouges, noirs, blancs et jaunes n'attendent qu'une chose : en découdre sur scène !\nVenez les voir s'affronter dans des matchs d'improvisation au sein de la Turbine ! \n\nÀ la fin, il n'y aura qu'un vainqueur…",
        "shortDescription": "Improvisem, notre championnat interne continue sa saison 2023-2024",
        "freeForStudents": false,
        "location": "La turbine - métro palais de justice",
        "imgLink": "https://luditoulouse.org/assets/logo/improvisem.png",
        "logoLink": "https://luditoulouse.org/assets/logo/improvisem.png",
        "bannerImgLink": "",
        "reservationLink": "",
        "facebookLink": "",
        "instagramLink": "",
        "isPublished": true,
        "isHighlighted": false,
        
        "price": 0,
        "reducedPrice": 0
    },
];
