import { Show } from "./../model";

export const show: Show[] = [
  {
    id: 3,
    name: "Match de rentrée ",
    date: 1695752100,
    description:
      "💥 !! C’EST LA RENTRÉE !!💥\nPublic, nous sommes de retour sur les planches de la salle Le Cap 🎭 !!\nEt on te prépare un match de rentrée inoubliable 😍\nSi tu ne connais pas le théâtre d’improvisation, ce sera une très belle occasion de le découvrir. Et qui sait, ça te donnera peut-être envie de nous rejoindre !! 🎭❤️",
    shortDescription:
      "Public, nous sommes de retour sur les planches de la salle Le Cap 🎭 !!\nEt on te prépare un match de rentrée inoubliable 😍",
    freeForStudents: true,
    location: "Salle Le CAP - Métro Paul Sabatier ",
    imgLink: "https://zupimages.net/up/22/36/sf3r.jpg",
    logoLink: "https://luditoulouse.org/assets/logo/match.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 5,
    reducedPrice: 0,
  },
  {
    id: 4,
    name: "Cours d'essai",
    date: 1696442400,
    description:
      "Tu as envie de découvrir ou de redécouvrir l'impro ?\nQue cette discipline te soit familière, ou complètement étrangère, tu es le bienvenu pour venir participer à nos quatre cours d'essai les :\n\n- Mercredi 4 octobre 2023 à 20h\n- Mercredi 11 octobre 2023 à 20h\n- Mercredi 18 octobre 2023 à 20h\n- Mercredi 25 octobre 2023 à 20h\n\nOn te donne RDV à ces dates dans le bâtiment U2 de l'université Paul Sabatier\nTu ne connais pas la fac et tu as peur de te perdre ? Aucun souci ! Des membres de l'association t'attendront aux arrêts de métro \"Paul Sabatier\" et \"Fac de Pharma\" à 20 h et t'accompagneront jusqu'au bâtiment U2 : promis, on te choisit les plus gentils !\n\nProfites-en, c'est GRATUIT !\n\nEt si tu es convaincu après ces quelques cours d'essai, tu pourras t'inscrire pour cette nouvelle saison 2023-2024 et rejoindre nos bancs !",
    shortDescription:
      "Viens découvrir l'impro, tu vas voir c'est stylé et pis c'est gratuit 😏",
    freeForStudents: false,
    location: "Bâtiment U2 Université Paul Sabatier ",
    imgLink: "https://zupimages.net/up/22/39/6h51.jpeg",
    logoLink:
      "https://i.ibb.co/ZSFNsNx/BDDD20-E8-06-C1-48-F2-BE9-B-27-C1-E80-BEF95.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink:
      "https://www.facebook.com/events/169997729204328/169998065870961/",
    instagramLink: "",
    isPublished: true,
    isHighlighted: true,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 5,
    name: "Cours d'essai",
    date: 1697047200,
    description:
      "Tu as envie de découvrir ou de redécouvrir l'impro ?\nQue cette discipline te soit familière, ou complètement étrangère, tu es le bienvenu pour venir participer à nos quatre cours d'essai les :\n\n- Mercredi 4 octobre 2023 à 20h\n- Mercredi 11 octobre 2023 à 20h\n- Mercredi 18 octobre 2023 à 20h\n- Mercredi 25 octobre 2023 à 20h\n\nOn te donne RDV à ces dates dans le bâtiment U2 de l'université Paul Sabatier\nTu ne connais pas la fac et tu as peur de te perdre ? Aucun souci ! Des membres de l'association t'attendront aux arrêts de métro \"Paul Sabatier\" et \"Fac de Pharma\" à 20 h et t'accompagneront jusqu'au bâtiment U2 : promis, on te choisit les plus gentils !\n\nProfites-en, c'est GRATUIT !\n\nEt si tu es convaincu après ces quelques cours d'essai, tu pourras t'inscrire pour cette nouvelle saison 2023-2024 et rejoindre nos bancs !",
    shortDescription:
      "Viens découvrir l'impro, tu vas voir c'est stylé et pis c'est gratuit 😏",
    freeForStudents: false,
    location: "Bâtiment U2 Université Paul Sabatier ",
    imgLink: "https://zupimages.net/up/22/39/6h51.jpeg",
    logoLink:
      "https://i.ibb.co/ZSFNsNx/BDDD20-E8-06-C1-48-F2-BE9-B-27-C1-E80-BEF95.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink:
      "https://www.facebook.com/events/169997729204328/169998065870961/",
    instagramLink: "",
    isPublished: true,
    isHighlighted: true,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 6,
    name: "Cours d'essai",
    date: 1697652000,
    description:
      "Tu as envie de découvrir ou de redécouvrir l'impro ?\nQue cette discipline te soit familière, ou complètement étrangère, tu es le bienvenu pour venir participer à nos quatre cours d'essai les :\n\n- Mercredi 4 octobre 2023 à 20h\n- Mercredi 11 octobre 2023 à 20h\n- Mercredi 18 octobre 2023 à 20h\n- Mercredi 25 octobre 2023 à 20h\n\nOn te donne RDV à ces dates dans le bâtiment U2 de l'université Paul Sabatier\nTu ne connais pas la fac et tu as peur de te perdre ? Aucun souci ! Des membres de l'association t'attendront aux arrêts de métro \"Paul Sabatier\" et \"Fac de Pharma\" à 20 h et t'accompagneront jusqu'au bâtiment U2 : promis, on te choisit les plus gentils !\n\nProfites-en, c'est GRATUIT !\n\nEt si tu es convaincu après ces quelques cours d'essai, tu pourras t'inscrire pour cette nouvelle saison 2023-2024 et rejoindre nos bancs !",
    shortDescription:
      "Viens découvrir l'impro, tu vas voir c'est stylé et pis c'est gratuit 😏",
    freeForStudents: false,
    location: "Bâtiment U2 Université Paul Sabatier ",
    imgLink: "https://zupimages.net/up/22/39/6h51.jpeg",
    logoLink:
      "https://i.ibb.co/ZSFNsNx/BDDD20-E8-06-C1-48-F2-BE9-B-27-C1-E80-BEF95.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink:
      "https://www.facebook.com/events/169997729204328/169998065870961/",
    instagramLink: "",
    isPublished: true,
    isHighlighted: true,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 1,
    name: "Match d'Impro",
    date: 1698172200,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La Turbine - Métro Palais de justice",
    imgLink: "",
    logoLink: "",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: true,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 7,
    name: "Cours d'essai",
    date: 1698256800,
    description:
      "Tu as envie de découvrir ou de redécouvrir l'impro ?\nQue cette discipline te soit familière, ou complètement étrangère, tu es le bienvenu pour venir participer à nos quatre cours d'essai les :\n\n- Mercredi 4 octobre 2023 à 20h\n- Mercredi 11 octobre 2023 à 20h\n- Mercredi 18 octobre 2023 à 20h\n- Mercredi 25 octobre 2023 à 20h\n\nOn te donne RDV à ces dates dans le bâtiment U2 de l'université Paul Sabatier\nTu ne connais pas la fac et tu as peur de te perdre ? Aucun souci ! Des membres de l'association t'attendront aux arrêts de métro \"Paul Sabatier\" et \"Fac de Pharma\" à 20 h et t'accompagneront jusqu'au bâtiment U2 : promis, on te choisit les plus gentils !\n\nProfites-en, c'est GRATUIT !\n\nEt si tu es convaincu après ces quelques cours d'essai, tu pourras t'inscrire pour cette nouvelle saison 2023-2024 et rejoindre nos bancs !",
    shortDescription:
      "Viens découvrir l'impro, tu vas voir c'est stylé et pis c'est gratuit 😏",
    freeForStudents: false,
    location: "Bâtiment U2 Université Paul Sabatier ",
    imgLink: "https://zupimages.net/up/22/39/6h51.jpeg",
    logoLink:
      "https://i.ibb.co/ZSFNsNx/BDDD20-E8-06-C1-48-F2-BE9-B-27-C1-E80-BEF95.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink:
      "https://www.facebook.com/events/169997729204328/169998065870961/",
    instagramLink: "",
    isPublished: true,
    isHighlighted: true,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 11,
    name: "MATCH D'IMPRO",
    date: 1699643700,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "Salle Le CAP - Métro Paul Sabatier ",
    imgLink: "https://luditoulouse.org/assets/logo/match.png",
    logoLink: "https://luditoulouse.org/assets/logo/match.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: true,

    price: 5,
    reducedPrice: 3,
  },
  {
    id: 15,
    name: "Championnat IMPROVISEM ",
    date: 1701199800,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 16,
    name: "Championnat IMPROVISEM ",
    date: 1701804600,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 14,
    name: "Spectacle de Noël ",
    date: 1702408500,
    description:
      "Vous aimez ces téléfilms de Noël ? Ces téléfilms un peu too much, un peu trop guimauve ? Eh bah, nous aussi, à là LUDI et c'est le thème de ce prochain spectacle d'Improvisation : Maman, j'ai raté l'IMPRO",
    shortDescription:
      "Vous aimez ces téléfilms de Noël ? Ces téléfilms un peu too much, un peu trop guimauve ? Eh bah, nous aussi, à là LUDI et c'est le thème de ce prochain spectacle d'Improvisation : Maman, j'ai raté l'IMPRO",
    freeForStudents: false,
    location: "Salle Le CAP - Métro Paul Sabatier ",
    imgLink: "https://luditoulouse.org/assets/logo/match.png",
    logoLink: "https://luditoulouse.org/assets/logo/match.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: true,

    price: 5,
    reducedPrice: 3,
  },
  {
    id: 17,
    name: "Championnat IMPROVISEM ",
    date: 1704828600,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 18,
    name: "Championnat IMPROVISEM ",
    date: 1706038200,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 20,
    name: "Championnat IMPROVISEM ",
    date: 1707852600,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 22,
    name: "Championnat IMPROVISEM ",
    date: 1710271800,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 31,
    name: "MATCH DES NOUVEAUX ",
    date: 1710962100,
    description:
      "Pour la première fois, nos nouveaux vont se lancer sur la patinoire,\nAlors n'hésite pas à venir les soutenir !\nIls débordent d'énergie, et pour la première fois, ils vont te faire rire, sourire, pleurer, t'intriguer, bref te partager de belles émotions !",
    shortDescription:
      "Pour la première fois, nos nouveaux vont se lancer sur la patinoire,\nAlors n'hésite pas à venir les soutenir !\nIls débordent d'énergie, et pour la première fois, ils vont te faire rire, sourire, pleurer, t'intriguer, bref te partager de belles émotions !",
    freeForStudents: false,
    location: "Salle Le CAP - Métro Paul Sabatier",
    imgLink: "https://i.ibb.co/1sHFcFV/image0.jpg",
    logoLink: "https://i.ibb.co/1sHFcFV/image0.jpg",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: true,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 23,
    name: "Championnat IMPROVISEM ",
    date: 1711481400,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 24,
    name: "Championnat IMPROVISEM ",
    date: 1712687400,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 25,
    name: "Championnat IMPROVISEM ",
    date: 1713897000,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 26,
    name: "Championnat IMPROVISEM ",
    date: 1715711400,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 33,
    name: "MATCH AVEC LA LIQA (Québec)",
    date: 1715969700,
    description:
      "MATCH D'IMPROVISATION : LUDI ✕ LIQA ✕ LEDI\n\nSpectateur de la LUDI de tous poils, nous vous appelons une dernière fois au CAP. Non, deux dernières fois au CAP !\nEt quoi de mieux que fêter ça que d'inviter deux ligues étrangères : La LIQA du Québec et la LEDI d'Italie !\n\nAu programme, un match d'improvisation avec la LIQA, en provenance tout droit du pays qui a vu naitre ce format ! (Oui oui, c'est vrai, vous pouvez fact-checker sur Google). \nJ'ai déjà vu des gens célèbres s'agenouiller devant eux (je ne peux vous dire lesquels sans risquer ma vie). Certaines contrées amérindiennes avaient érigé un culte à leur égard, dressant des statues d'eux à l'entrée de leurs temples. Aussi, des théories scientifiques très sérieuses prétendent même expliquer les origines de l'univers en le reliant à la création de la LIQA.\n\nQuant à la LEDI, c'est un peu la cinquième symphonie qui aurait rencontré Pasolini. Grosso modo. Quand ils arrivent, il y a tout un charme latin qui s'empare du CAP, le DJ se met à jouer de la mandolino. Les comédiens alternent entre comédie grand guignol et drame néoréaliste. Et le public repart en s'étant fait voler leur coupe du monde (oui ça va, je déconne).\n\nPour résumer, c'est la dernière de l'année. Oui, je le répète, mais c'est parce que je suis triste et on a envie de te voir une dernière fois avant les vacances PUBLIC :)",
    shortDescription: "",
    freeForStudents: false,
    location: "Salle Le CAP - Métro Paul Sabatier ",
    imgLink: "https://i.ibb.co/5GRs0qF/Annonce-Match-LIQA-LEDI.png",
    logoLink: "https://luditoulouse.org/assets/logo/match.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 5,
    reducedPrice: 3,
  },
  {
    id: 21,
    name: "Championnat IMPROVISEM ",
    date: 1716921000,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 27,
    name: "Championnat IMPROVISEM - PETITE FINALE",
    date: 1718130600,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,

    price: 0,
    reducedPrice: 0,
  },
  {
    id: 28,
    name: "Championnat IMPROVISEM - GRANDE FINALE",
    date: 1719340200,
    description: "",
    shortDescription: "",
    freeForStudents: false,
    location: "La turbine - métro palais de justice",
    imgLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    logoLink: "https://luditoulouse.org/assets/logo/improvisem.png",
    bannerImgLink: "",
    reservationLink: "",
    facebookLink: "",
    instagramLink: "",
    isPublished: true,
    isHighlighted: false,
    price: 0,
    reducedPrice: 0,
  },
];
